spring.application.name=erd
spring.config.import=optional:file:./database.properties

spring.datasource.url=${database.url}
spring.datasource.username=${database.username}
spring.datasource.password=${database.password}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.thymeleaf.cache=false
server.error.include-message=always
